[package]
name = "RustLinearFold"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["yakuhito <y@kuhi.to>"]
homepage = "https://github.com/Yakuhito/RustLinearFold"
repository = "https://github.com/Yakuhito/RustLinearFold"

[dependencies]
